name: My first Action
on: [push,workflow_dispatch]

jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
    - name: print greeting
      run: echo "hello world1"
    
    - name: Explore Food
      run: echo "I want to eat"
    
    - name: Make Payment
      run: echo "Make payment of $50"
     